AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "vendor/**/*"
    - "spec/**/*"

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 150
